### ISSUE TITLE
Surface sample while flying...?

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#18]
**Describe the bug**
<img width="957" alt="Bildschirmfoto 2019-04-03 um 18 00 52" src="https://user-images.githubusercontent.com/43166475/55494124-7c005800-563a-11e9-900b-6ffac122ce23.png">

**Comment by UsernamesAreAlwaysTaken** [comment]
this is because the situation mask is messed up. needs situationmask=1 in experiment config. easily fixable.

**Comment by UsernamesAreAlwaysTaken** [comment]
okay, tested this, this is not exclusive to surface sample. This applies to all experiments. Somehow, the game ignores the situation masks and thnks that it's possible to get science everywhere and anywhere for all experiments

Experiment just limits where data can be collected, but the game thinks otherwise.
This is not a config issue, this is plugin. Situation masks are defined properly in my configs.

**Comment by SirMortimer** [comment]
I think it's fixed.
