### ISSUE TITLE
Orbital Survey bypasses hard drives

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [SirMortimer/Kerbalism#76]
![asdasdasdasd](https://user-images.githubusercontent.com/48958828/57317028-0f6ff180-70ef-11e9-8c58-75a4dde4f194.gif)

I believe the image is self-explanatory.

The issue that arises from this: no background tranmission is possible. This becomes major when you factor in the antenna bandwidth nerfs. For kerbin, with a RA-100, you'd probably need an orbit or 2, while having the vessel active, to transmit the data back.

Now think about eelo. (probably timewarp for a few months with vessel active to transmit data. If  connection is lost, afaik you have to restart from scratch. Fun times.

**Comment by gotmachine** [comment]
Not the case, the stock module completely bypass our transmission rates, it uses the stock rates and is unaffected by Kerbalism.
Still, we could have add some support for the stock scanner.
It should possible to make a derived class from the ModuleOrbitalSurveyor and add lightweight support since all the methods are virtual.

Specifically we should :
- override OnAwake with the following : 
`perfSurv = base.Events["PerformSurvey"];` 
- override OnDestroy with an empty method
- override sendDataToComms() and make it create (instantly) a file with a size of :
 `vessel.mainBody.Radius * 0.001 / ScanTime;`
  with the subject_id :
`"survey@" + vessel.mainBody.bodyName`
- add the following to a static method called in Science.Update when the file has been fully transmitted : 
```
post message : Localizer.Format("#autoLOC_259361", body.displayName);
ResourceMap.Instance.UnlockPlanet(body.flightGlobalsIndex);
```

**Comment by UsernamesAreAlwaysTaken** [comment]
```override sendDataToComms() and make it create (instantly) a file with a size of :
vessel.mainBody.Radius * 0.001 / ScanTime;``` This would work, but IMO make the 0.001 multiplier patchable for balance reasons. Some random orbital experiments would take up more drive capacity than a survey, which would make little sense. The survey is probably by far the most useful bit of info, so it should have a pretyt high data scale. Instead of me asking you to change the code every time, let me patch it through MM, because i assume it'll take a few attempts till we get it right.

Other than that, the formula makes sense.

Question: As it'll be forced through the drives now, would our data tranmission rates kick in? Or would it have it's own transmission mechanics?

**Comment by SirMortimer** [comment]
Anything that goes through our drives is subjected to our transmission rates.

I'd suggest something that goes a bit further:
- Create our own part module for orbital surveys, as @gotmachine described above
- Add to that a background update method that just generates data at a configured rate (that could later be made depending on the type of orbit)

For patching/balancing purposes, the total file size and data generation rates should be configurable with our extended scanner part module. Also, the file size should be depending on the size of the body.

Unlock the overlay map only when the file has been fully-ish (maybe min. 90% received?) transmitted, somewhere in Science.Update.

**Comment by UsernamesAreAlwaysTaken** [comment]
Works for me. I'd still like to request the gradually generated overlays (in the future, whenever possible), as i'd still like to have separate scanner configs for each resource through a configure module, which will generate its own overlay and give some science.

**Comment by SirMortimer** [comment]
migrated
