### ISSUE TITLE
Allow Lab to reset samples

### ISSUE THREAD

**Issue by SirMortimer** [SirMortimer/Kerbalism#9]
Currently a goo canister, once depleted, cannot be restored. The sampling material therein must be replaced first.

Allow the Lab to refill sampling experiments. A refill should use up a new resource "Sampling Material" that can be stored in the Lab itself and non-pressurized containers (it's not a gas). It also should be a VERY expensive resource.

**Comment by UsernamesAreAlwaysTaken** [comment]
As discussed, instead of adding new resources and processes to manufacture those resources, prevent samples being reset before the sample is analyzed in a lab. 
For experiments that have sample_collecting = false (the ones that do not generate mass), the sample needs to be analyzed in a lab before it can be reset. The mass doesn;t get "jettissoned out of the airlock", but instead gets placed back in the experiment as it gets analyzed. For the ones that do generate mass, that mass should be jettisoned out of the airlock once analyzed.

This keeps the mass in check without neediing new resources and the added complexity.

**Comment by SirMortimer** [comment]
I think it's fixed.
